name: Node

concurrency:
    group: Node-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    push:
        branches: [Current]
    pull_request:
        branches: [Current]
    workflow_call:

jobs:
    Pre-Publish:
        runs-on: ubuntu-latest

        env:
            ADBLOCK: true
            ASTRO_TELEMETRY_DISABLED: 1
            AUTOMATEDLAB_TELEMETRY_OPTOUT: 1
            AZURE_CORE_COLLECT_TELEMETRY: 0
            CHOOSENIM_NO_ANALYTICS: 1
            DIEZ_DO_NOT_TRACK: 1
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
            DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT: 1
            DO_NOT_TRACK: 1
            ET_NO_TELEMETRY: 1
            GATSBY_TELEMETRY_DISABLED: 1
            GATSBY_TELEMETRY_OPTOUT: 1
            GATSBY_TELEMETRY_OPT_OUT: 1
            GRIT_TELEMETRY_DISABLED: 1
            HASURA_GRAPHQL_ENABLE_TELEMETRY: false
            HINT_TELEMETRY: off
            HOMEBREW_NO_ANALYTICS: 1
            INFLUXD_REPORTING_DISABLED: true
            ITERATIVE_DO_NOT_TRACK: 1
            NEXT_TELEMETRY_DEBUG: 1
            NEXT_TELEMETRY_DISABLED: 1
            NG_CLI_ANALYTICS: false
            NUXT_TELEMETRY_DISABLED: 1
            PIN_DO_NOT_TRACK: 1
            POWERSHELL_TELEMETRY_OPTOUT: 1
            SAM_CLI_TELEMETRY: 0
            STNOUPGRADE: 1
            STRIPE_CLI_TELEMETRY_OPTOUT: 1
            TELEMETRY_DISABLED: 1
            TERRAFORM_TELEMETRY: 0

        strategy:
            matrix:
                node-version: [18, 19, 20]

        steps:
            - uses: actions/checkout@v4.1.7

            - uses: pnpm/action-setup@v4.0.0
              with:
                  version: 9.3.0
                  run_install: |
                      - recursive: true
                        args: [
                          --link-workspace-packages=true,
                          --lockfile-only,
                          --prefer-frozen-lockfile=false,
                          --shamefully-hoist=false,
                          --shared-workspace-lockfile=true,
                          --strict-peer-dependencies=false,
                          --unsafe-perm=true
                        ]

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./default/component-gallery/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./default/component-gallery

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./default/editable-data-grid/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./default/editable-data-grid

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./default/hello-world-webpack/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./default/hello-world-webpack

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./default/hello-world/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./default/hello-world

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./default/notepad/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./default/notepad

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./default/weather-webview/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./default/weather-webview

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./frameworks/component-gallery-react/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./frameworks/component-gallery-react

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./frameworks/component-gallery-react/webview-ui/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./frameworks/component-gallery-react/webview-ui

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-frameworks-component-gallery-react-webview-ui-Node-${{ matrix.node-version }}-Target
                  path: ./frameworks/component-gallery-react/webview-ui/Target

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./frameworks/hello-world-angular/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./frameworks/hello-world-angular

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./frameworks/hello-world-angular/webview-ui/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./frameworks/hello-world-angular/webview-ui

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-frameworks-hello-world-angular-webview-ui-Node-${{ matrix.node-version }}-Target
                  path: ./frameworks/hello-world-angular/webview-ui/Target

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./frameworks/hello-world-react-cra/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./frameworks/hello-world-react-cra

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./frameworks/hello-world-react-cra/webview-ui/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./frameworks/hello-world-react-cra/webview-ui

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-frameworks-hello-world-react-cra-webview-ui-Node-${{ matrix.node-version }}-Target
                  path: ./frameworks/hello-world-react-cra/webview-ui/Target

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./frameworks/hello-world-react-vite/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./frameworks/hello-world-react-vite

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./frameworks/hello-world-react-vite/webview-ui/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./frameworks/hello-world-react-vite/webview-ui

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-frameworks-hello-world-react-vite-webview-ui-Node-${{ matrix.node-version }}-Target
                  path: ./frameworks/hello-world-react-vite/webview-ui/Target

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./frameworks/hello-world-solidjs/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./frameworks/hello-world-solidjs

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./frameworks/hello-world-solidjs/webview-ui/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./frameworks/hello-world-solidjs/webview-ui

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-frameworks-hello-world-solidjs-webview-ui-Node-${{ matrix.node-version }}-Target
                  path: ./frameworks/hello-world-solidjs/webview-ui/Target

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./frameworks/hello-world-svelte/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./frameworks/hello-world-svelte

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./frameworks/hello-world-svelte/webview-ui/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./frameworks/hello-world-svelte/webview-ui

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-frameworks-hello-world-svelte-webview-ui-Node-${{ matrix.node-version }}-Target
                  path: ./frameworks/hello-world-svelte/webview-ui/Target

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./frameworks/hello-world-vue/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./frameworks/hello-world-vue

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./frameworks/hello-world-vue/webview-ui/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./frameworks/hello-world-vue/webview-ui

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-frameworks-hello-world-vue-webview-ui-Node-${{ matrix.node-version }}-Target
                  path: ./frameworks/hello-world-vue/webview-ui/Target
